### PR TITLE
Fix for Could not evaluate: undefined method `each' for "1\n":String on Ruby 1.9 and higher

### PR DESCRIPTION
**Pull request by hajee**
Ruby 1.9 doesn't support each on a String. It is changed to .each_line

### CODE REVIEW

**Comment by akumria** [comment]
Thanks, I just have to confirm that this still works on Ruby 1.8 and I'll merge.

**Comment by guilhermef** [comment]
I've got the same error.
Any thoughts ?

**Comment by akumria** [comment]
Hi Guilherme,

Thanks for the reminder, this slipped off my radar.

Does the proposed fix work for you?

If so, I'll merge in Bert's changes and release later tonight.

A

On 11 December 2012 13:07, Guilherme Souza notifications@github.com wrote:

> I've got the same error.
> Any thoughts ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/akumria/puppet-postgresql/pull/15#issuecomment-11242611.

## 

“Don’t be sad because it’s over. Smile because it happened.” – Dr. Seuss

**Comment by guilhermef** [comment]
Hey akumria,
sure this fix works perfectly.
Thanks for that.
